name: Job Id
description: Get Job Id and Step Number

inputs:
  job_name:
    description: Job Name
    required: true
  step_name:
    description: Step Name
    required: false

runs:
  using: 'composite'
  steps:
    - name: Get Current Job Log URL
      id: jobs
      env:
        JOB_NAME: "${{ inputs.job_name }}"
        STEP_NAME: "${{ inputs.step_name }}"
      shell: bash
      run: |
        GITHUB_API="/repos/${INPUT_REPOSITORY:-${GITHUB_REPOSITORY}}/actions/runs/${INPUT_RUN_ID:-${GITHUB_RUN_ID}}/jobs"
        JOBINFO="$(curl --get -Ss -H "Authorization: ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "${GITHUB_API_URL}${GITHUB_API}?per_page=${INPUT_PER_PAGE:-30}")"
        echo "${JOBINFO}" | grep "Resource not accessible by integration" &&  exit 1
        eval "$(echo ${JOBINFO} | jq -r --arg job_name "${JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "job_id=\(.id) html_url=\(.html_url)"')"
        echo ${job_id} | grep "null" > /dev/null && echo "parse error, job_id is ${job_id}. job name might be wrong. See https://github.com/Tiryoh/gha-jobid-action" && exit 1
        
        echo "job_id=${job_id}" >> $GITHUB_OUTPUT
        echo "html_url=${html_url}" >> $GITHUB_OUTPUT

        if [[ -n "${STEP_NAME}" ]]; then
          eval "$(echo ${JOBINFO} | jq -r --arg job_name "${JOB_NAME}" --arg step_name "${STEP_NAME}" \
            '.jobs | map(select(.name | contains($job_name))) | .[0] | .steps | map(select(.name == $step_name))| .[0] | @sh "step_number=\(.number)"')"
          echo "step_number=${step_number}" >> $GITHUB_OUTPUT
        fi
      
        echo "job_id=${job_id}" >> $GITHUB_OUTPUT
        echo "html_url=${html_url}" >> $GITHUB_OUTPUT
