name: Detect Changed Action

on:
  push:
    tags:
      - '*'

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write
  actions: write
  security-events: write

env:
  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:
  detect-changed-action:
    name: Detect Changed Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⇣ Search for changed actions
        shell: bash
        id: config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh label create dependencies --description "Update dependencies" --color FBCA04 --force
          branch_name=`date '+%Y%m%d_%H%M%S'`_update
          git fetch origin
          git checkout -B main origin/main
          git pull --unshallow
          git config --global user.email "devx_arcadia@arcadia.io"
          git config --global user.name "DevX Updater"
          pr_num=`git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1| sed -En "s/.*#([[:digit:]]+).*/\1/p"`
          echo pr_num: $pr_num
          files=`gh pr diff $pr_num --name-only| grep -v '(.github|README|.git)'`
          if [[ $? == "0" ]];then
            latest_tag=`git describe --tags --abbrev=0`
            git checkout -B "$branch_name" origin/main
            for file in $files; do
              action_name=`dirname $file`
              grep -rl "$action_name@" . || continue
              update_files=`grep -rl "$action_name@" . | grep -v '(.github|README|.git)'`
              echo $update_files | xargs sed -i "s|$action_name@.*|$action_name@$latest_tag|g"
              echo $update_files | xargs git add
            done
            pr_body="**Update github actions** to new version **$latest_tag**"
            git commit -m "fix: update versions to $latest_tag" &&
            git push origin -u "$branch_name" &&
            gh pr create --title "Update apentsak-vitech/gh-checks actions to $latest_tag" --body "$pr_body" --base main --label "dependencies" || echo !!! No files were updated !!!
          fi
