name: Terragrunt PET

on: pull_request

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write
  actions: write
  security-events: write

env:
  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:

  define-targets:
    name: Test Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terragrunt HCL Log
        uses: apentsak-vitech/gh-checks/github/publish-checks@main
        with:
          name: Terragrunt HCL Log
          conclusion: success
          description-file: terraform1.md

      - name: Terragrunt HCL Log
        uses: apentsak-vitech/gh-checks/github/publish-checks@main
        with:
          name: Terragrunt HCL Log
          conclusion: success
          description-file: terraform2.txt
