name: Detect Changed Action

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write
  actions: write
  security-events: write

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  detect-changed-action:
    name: Detect Changed Actions
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
#        with:
#          token: ${{ env.PAT_TOKEN }}
      - name: ⇣ Search for changed actions
        shell: bash
        id: config
        env:
          GH_TOKEN: ${{ env.PAT_TOKEN }}
        run: |
          if ! [[ -z "${{ env.GH_TOKEN }}" ]]; then
            echo GH_TOKEN=true
          else
            echo GH_TOKEN=false
          fi
          if ! [[ -z "${{ secrets.PAT_TOKEN }}" ]]; then
            echo secretsPAT_TOKEN=true
          else
            echo secretsPAT_TOKEN=false
          fi
          if ! [[ -z "${{ env.PAT_TOKEN }}" ]]; then
            echo PAT_TOKEN=true
          else
            echo PAT_TOKEN=false
          fi
          
          git fetch origin
          git checkout -B main origin/main
          git pull --unshallow
          git config --global user.email "devx_arcadia@arcadia.io"
          git config --global user.name "DevX Updater"
          echo TEST > `date '+%N'`.txt
          git add .
          git commit -m "fix: TEST!!!" &&
          git push origin -u main || echo !!! No files were updated !!!
          
