name: Detect Changed Action

on:
  push:
    branches:
      - dev

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write
  actions: write
  security-events: write

jobs:
  detect-changed-action:

    name: Detect Changed Actions
    runs-on: ubuntu-latest
    environment: test
    steps:
      - id: vars
        uses: apentsak-vitech/gh-checks/github/br@dev

          
#          git fetch origin
#          git checkout -B main origin/main
#          git pull --unshallow
#          git config --global user.email "devx_arcadia@arcadia.io"
#          git config --global user.name "DevX Updater"
#          echo TEST > `date '+%N'`.txt
#          git add .
#          git commit -m "fix: TEST!!!" &&
#          git push origin -u main || echo !!! No files were updated !!!
          
